### ISSUE TITLE
Feature request: warning on too many pins in product terms

### ISSUE THREAD

**Issue by electrickery** [daveho/GALasm#15] opened 2022-04-24 14:02 UTC
This might not really be a bug, but it is somewhat inconvenient and less than helpful.

If a line in a .pld file contains too many pins in a product term, the extra's are silently ignored.

This in contrast with the count of product terms which is checked.

The following .pld file defines six outputs, each defined with a single product term containing nine pins. The last one is silently ignored. Assuming the code knows about the maximum number of terms per device, a warning would be helpful for the user.

		GAL16V8    ; Address decode
		ADDRDC4  ;
		
		;1    2     3     4     5     6     7     8     9     10
		NC  /IORQ  /WR   A0    A1    A2    A3    A4    A5    GND
		NC   Q0    Q1   Q2    Q3    Q4    Q5    A6    A7     VCC
		;11  12    13   14    15    16    17    18    19     20
		
		Q0 = /A0 * /A1 * /A2 * IORQ * WR * A3 * A4 * A5 * A6
		Q1 =  A0 * /A1 * /A2 * IORQ * WR * A3 * A4 * A5 * A6
		Q2 = /A0 *  A1 * /A2 * IORQ * WR * A3 * A4 * A5 * A6
		Q3 =  A0 *  A1 * /A2 * IORQ * WR * A3 * A4 * A5 * A6
		Q4 = /A0 * /A1 *  A2 * IORQ * WR * A3 * A4 * A5 * A6
		Q5 =  A0 * /A1 *  A2 * IORQ * WR * A3 * A4 * A5 * A6
		
		DESCRIPTION
		
But when a pin is defined with too many product terms, like the attached file, GALasm throws an error:

		Error in line 54: too many product terms
		
Simplyfied versions of attached file did compile, but the GAL didn't work, this might be related with the issue described above, or I don't really understand registered mode (the latter is most likely).

[RINCREMENTER1.pld.txt](https://github.com/daveho/GALasm/files/8549831/RINCREMENTER1.pld.txt)

**Comment by pjdennis** [comment] 2022-04-24 18:22
@electrickery there's no limit on the number of pins included in a product term - you can include all available inputs and feedbacks. I suggest looking for another reason for the behavior you're seeing - test the GAL in isolation with the simple example you pasted above; try using a different device or different pin for A6 in case that pin is bad.

I tried out the 'address decode' example that you pasted and it works for me (well I'm using a 20V8 since I don't have a 16V8 but they are very similar.) You should also see that the .jed file is different if you leave off 'A6' from the end of the product term.

**Comment by electrickery** [comment] 2022-04-25 06:55
It appears all GAL16V8's I tried (seven of them!) have a broken pin 15 :-(.

**Comment by pjdennis** [comment] 2022-04-27 11:13
@electrickery there are pin-specific constraints with the GAL16V8, for example using pins 15 or 16 as inputs would preclude 'simple' mode. Of course you can see these constraints in the datasheet. The galasm in this repo will display the reasons for mode selection if you use the -v option.

One thing to keep in mind for registered mode on the GAL16V8 is that pin 1 is fixed as a common clock for the D flip flops making up the registers, and pin 11 is fixed as a common output enable. This may be at least part of the problem with your RINCREMENTER design.

**Comment by pjdennis** [comment] 2022-04-27 11:31
Closing this issue - I'm not seeing the behavior described and have confirmed the example in the original comment works as expected with 290d0cf9dcd0d9749167c9019ad694db2c3360dd - the state of Q0..Q5 is affected by A6 (used GAL20V8 as that's what I have, but also confirmed the .jed file output is affected by including A6, for the 16V8.)

If there's additional details to reproduce the issue, or another situation where galasm silently ignores pins, feel free to reopen or open a new issue.

**Closed by pjdennis** 2022-04-27 11:31 UTC
Labels: invalid
