### ISSUE TITLE
Checksum Ok for GAL16V8 but not for GAL22V10

### ISSUE THREAD

**Issue by electrickery** [daveho/GALasm#14] opened 2022-04-22 09:47 UTC
[INCREMENTER5.pld.zip](https://github.com/daveho/GALasm/files/8541780/INCREMENTER5.pld.zip)
A GAL16V8 .pld file assembled to .jed is accepted by the https://gitlab.com/DavidGriffith/minipro programmer software and the GAL appears to work as expected. But my GAL22V10 .pld file is not. The problem appears to be a wrong file checksum. The checksum in the GAL16V8 file is four hex digits, but in the GAL22V10 file is five digits. Replacing the value by the one suggested by the minipro software results in a accepted .jed file, which can be programmed. As an experimental test, a quick hack in jedec.c:FileChecksum() truncating the checksum to 4 digits appears to be working to:

    checksum = checksum & 0xFFFF;

On the minipro gitlab site is a link to a .jed file specification (http://www.pldtool.com/pdf/fmt_jedec.pdf), and it indeed specifies a four digit file checksum.

Greetings,
Fred Jan

Edit: Attached the offending pld file.

**Comment by pjdennis** [comment] 2022-04-22 13:49
@electrickery could you attach the .pld file that's resulting in an invalid checksum? If you don't mind sharing, of course.

**Comment by pjdennis** [comment] 2022-04-22 15:16
@electrickery could you make sure you have the latest code from master, especially commit c9ae0b94103187840e3103e593d6259a696907e4 which introduced a fix for the file checksum calculation to wrap to 16 bits:

`*pchecksum = (*pchecksum + (UBYTE) c) % 0x10000;`

I've tested INCREMENTER5.pld with the latest code (290d0cf9dcd0d9749167c9019ad694db2c3360dd) and it produces the correct file checksum as confirmed by Minipro.

Minipro output for INCREMENTER5.jed with Windows line endings:

```
Declared fuse checksum: 0xF343 Calculated: 0xF343 ... OK
Declared file checksum: 0xEAE9 Calculated: 0xEAE9 ... OK
```
... and for INCREMENTER5.jed with mac/unix line endings:
```
Declared fuse checksum: 0xF343 Calculated: 0xF343 ... OK
Declared file checksum: 0xE804 Calculated: 0xE804 ... OK
```

**Comment by electrickery** [comment] 2022-04-22 16:34
@pjdennis found the problem, my clone was for a different non-fork of the same original code base:

$ git remote -v
origin	https://github.com/dwery/galasm.git (fetch)
origin	https://github.com/dwery/galasm.git (push)

I'm very sorry I posted the issue to the wrong repository. Git(hub) can be very confusing. The issue does not apply to your repository.

Greetings,
Fred Jan

**Comment by pjdennis** [comment] 2022-04-22 17:49
@electrickery no worries; it was interesting to see the incrementer logic in INCREMENTER5.pld.

Closing since this is not an issue with the code in this repo.

**Closed by pjdennis** 2022-04-22 17:49 UTC
Labels: invalid
